[tool.poetry]
name = "munkey"
version = "0.1.0"
description = "Software to manage MUN conferences"

authors = [
    "DMUN e.V. <support@dmun.de>"
]

[tool.poetry.dependencies]
python = "^3.6"
Django = "^2.0"
black = "^19.10b0"
wagtail = "^2.8"
