# Generated by Django 2.2.7 on 2020-02-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munkeyuser',
            name='committee',
            field=models.ManyToManyField(to='paper_management.Committee'),
        ),
    ]
