name: munkey

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install
        which poetry
    - name: Lint with black
      run: |
        source $HOME/.poetry/env
        $HOME/.poetry/bin/poetry run black --check .
    - name: Test apps
      run: |
        cp .env.example .env
        $HOME/.poetry/bin/poetry run coverage run manage.py test munkey paper_management homepage
    - name: Upload coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: $HOME/.poetry/bin/poetry run coveralls